### ISSUE TITLE
Preview with Touch Bar and screen recording

### ISSUE THREAD

**Issue by rodrigobdz** [floor114/zsh-apple-touchbar#3]
I could not find a program to record screen and Touch Bar simultaneously. How did you make this preview?

![preview](https://user-images.githubusercontent.com/14152377/49331438-30ab3f80-f59d-11e8-8916-308f46b2cced.gif)

**Comment by floor114** [comment]
It's a touch bar simulator. I don't remember which one exactly.

**Comment by floor114** [comment]
And please do not create issues that are not related to the project.

**Comment by rodrigobdz** [comment]
> And please do not create issues that are not related to the project.

Technically, it's related to zsh-apple-touchbar's preview.
